name: url-shortener-server

services:
  # PostgreSQL
  url-shortener-db:
    image: postgres:16-alpine
    container_name: url-shortener-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d url_shortener_db -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
    networks:
      - url-shortener-network
  # Redis
  url-shortener-cache:
    image: redis:7-alpine
    container_name: url-shortener-cache
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - url_shortener_cache_data:/data
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

volumes:
  url_shortener_cache_data: